version: '3'

services:
  pg_db:
    image: postgres:latest
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env.db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
  
      
volumes:
  pgdata:
  pgadmindata:

